from fastapi.testclient import TestClient

from src.app import app, activities

# Tests generated by Copilot.

client = TestClient(app)


def reset_activities():
    activities.clear()
    activities.update(
        {
            "Chess Club": {
                "description": "Learn strategies and compete in chess tournaments",
                "schedule": "Fridays, 3:30 PM - 5:00 PM",
                "max_participants": 12,
                "participants": ["michael@mergington.edu", "daniel@mergington.edu"],
            },
            "Programming Class": {
                "description": "Learn programming fundamentals and build software projects",
                "schedule": "Tuesdays and Thursdays, 3:30 PM - 4:30 PM",
                "max_participants": 20,
                "participants": ["emma@mergington.edu", "sophia@mergington.edu"],
            },
        }
    )


def test_signup_duplicate_is_rejected():
    reset_activities()

    response = client.post("/activities/Chess Club/signup?email=michael@mergington.edu")

    assert response.status_code == 400
    assert response.json()["detail"] == "Student is already signed up for this activity"


def test_signup_rejects_non_mergington_email():
    reset_activities()

    response = client.post("/activities/Chess Club/signup?email=student@gmail.com")

    assert response.status_code == 400
    assert response.json()["detail"] == "Only students from Mergington High School can sign up"


def test_remove_participant_from_activity():
    reset_activities()

    response = client.delete("/activities/Chess Club/participants?email=daniel@mergington.edu")

    assert response.status_code == 200
    assert response.json()["message"] == "Removed daniel@mergington.edu from Chess Club"
    assert "daniel@mergington.edu" not in activities["Chess Club"]["participants"]
